### ISSUE TITLE
Train a new g2p-seq2seq model 

### ISSUE THREAD

**Issue by cbsandeep10** [cmusphinx/g2p-seq2seq#106]
I am trying to train a model on a english dictionary from cmusphinx.
 **g2p-seq2seq --train cmudict.0.7a --model-dir en-in-model**

python --version : 2.7
pip --version : 8.1.1
tensorflow-gpu --version : 1.4.0
cuda --verison : 8.0

I get the following error : 
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==6.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.0.0a0-py2.7.egg/g2p_seq2seq/app.py", line 72, in <module>
    tf.flags.DEFINE_integer("eval_steps", 10, "Number of steps for evaluation.")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 112, in DEFINE_integer
    _define_helper(flag_name, default_value, docstring, int)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 86, in _define_helper
    type=flagtype)
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --eval_steps: conflicting option string(s): --eval_steps

**Comment by nshmyrev** [comment]
@nurtas-m waiting for your reply here

**Comment by cbsandeep10** [comment]
Forgive me for the late reply. I was able to train and decode successfully upon reinstalling tensorflow. 

Thank you so much.

**Comment by nishant260190** [comment]
assert data_dir
AssertionError

I got the above mentioned assertion error and it is resolved by putting dict file in a folder as told here 
https://github.com/cmusphinx/g2p-seq2seq/issues/119#issuecomment-387062957
