### ISSUE TITLE
ValueError: too many values to unpack (g2p-seq2seq --interactive)

### ISSUE THREAD

**Issue by loretoparisi** [cmusphinx/g2p-seq2seq#112]
Hello @nurtas-m and @nshmyrev I have completed the training (just a test) of the CMU 2 IPA dictionary (current master branch), I can see model's checkpoint, meta, etc., but I get this error in inference:

```
# g2p-seq2seq --interactive --model_dir data/models/cmudict-ipa-64 
INFO:tensorflow:Importing user module g2p_seq2seq from path /usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.0a0-py2.7.egg
[2018-04-24 14:28:22,548] Importing user module g2p_seq2seq from path /usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.0a0-py2.7.egg
INFO:tensorflow:Overriding hparams in transformer_base with eval_drop_long_sequences=1,batch_size=4096,num_hidden_layers=2,hidden_size=64,filter_size=256,num_heads=4,length_bucket_step=1.5,max_length=30,min_length_bucket=6
[2018-04-24 14:28:22,551] Overriding hparams in transformer_base with eval_drop_long_sequences=1,batch_size=4096,num_hidden_layers=2,hidden_size=64,filter_size=256,num_heads=4,length_bucket_step=1.5,max_length=30,min_length_bucket=6
INFO:tensorflow:schedule=train_and_evaluate
[2018-04-24 14:28:22,552] schedule=train_and_evaluate
INFO:tensorflow:worker_gpu=1
[2018-04-24 14:28:22,552] worker_gpu=1
INFO:tensorflow:sync=False
[2018-04-24 14:28:22,552] sync=False
WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
[2018-04-24 14:28:22,552] Schedule=train_and_evaluate. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
[2018-04-24 14:28:22,552] datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
[2018-04-24 14:28:22,552] caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
[2018-04-24 14:28:22,553] ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 1, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6df0cea450>, '_keep_checkpoint_every_n_hours': 1, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 2000, '_environment': 'local', '_master': '', '_model_dir': 'data/models/cmudict-ipa-64', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f6df6e2f150>, '_save_summary_steps': 100}
[2018-04-24 14:28:22,553] Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 1, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6df0cea450>, '_keep_checkpoint_every_n_hours': 1, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 2000, '_environment': 'local', '_master': '', '_model_dir': 'data/models/cmudict-ipa-64', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f6df6e2f150>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f6df0cedf50>) includes params argument, but params are not passed to Estimator.
[2018-04-24 14:28:22,553] Estimator's model_fn (<function wrapping_model_fn at 0x7f6df0cedf50>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using ValidationMonitor
[2018-04-24 14:28:22,554] Using ValidationMonitor
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
[2018-04-24 14:28:22,733] From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 1, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6df0cea450>, '_keep_checkpoint_every_n_hours': 1, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 2000, '_environment': 'local', '_master': '', '_model_dir': 'data/models/cmudict-ipa-64', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f6df6e2f150>, '_save_summary_steps': 100}
[2018-04-24 14:28:22,734] Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 1, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6df0cea450>, '_keep_checkpoint_every_n_hours': 1, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, 'use_tpu': False, '_tf_random_seed': None, '_num_worker_replicas': 0, '_task_id': 0, 't2t_device_info': {'num_async_replicas': 1}, '_evaluation_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_save_checkpoints_steps': 2000, '_environment': 'local', '_master': '', '_model_dir': 'data/models/cmudict-ipa-64', 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x7f6df6e2f150>, '_save_summary_steps': 100}
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f6df0c85578>) includes params argument, but params are not passed to Estimator.
[2018-04-24 14:28:22,734] Estimator's model_fn (<function wrapping_model_fn at 0x7f6df0c85578>) includes params argument, but params are not passed to Estimator.
> home
WARNING:tensorflow:Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
[2018-04-24 14:28:31,779] Input graph does not contain a QueueRunner. That means predict yields forever. This is probably a mistake.
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==6.1.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.0a0-py2.7.egg/g2p_seq2seq/app.py", line 111, in main
    g2p_model.interactive()
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.0a0-py2.7.egg/g2p_seq2seq/g2p.py", line 248, in interactive
    self.__prepare_interactive_model()
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.0a0-py2.7.egg/g2p_seq2seq/g2p.py", line 173, in __prepare_interactive_model
    input_fn, estimator_lib.model_fn_lib.ModeKeys.PREDICT)
ValueError: too many values to unpack
```

**Comment by nurtas-m** [comment]
Can you, please, download the latest version of g2p-seq2seq (6.1.2a0)

**Comment by loretoparisi** [comment]
@nurtas-m when I run `python setup.py install` on the master branch I see this log 

```
Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for g2p-seq2seq==6.1.0a0
```

is that correct?

**Comment by nurtas-m** [comment]
No, you should clone and install the latest version of g2p-seq2seq (6.1.3a0)

**Comment by loretoparisi** [comment]
@nurtas-m hello, thanks I have created from scratch the docker container to be sure I'm workin on the master copy, so I'm using the build `6.1.3a0`. I did from scratch the model with the default configuration and the CMU dictionary. I can see the training file in the dict folder:

```
root@04a9cdd20f2d:~/g2p-seq2seq# ls -l /root/data/dict/cmudict   
total 12400
-rw-rw-r-- 1 1000 1000 3615936 Mar 27 09:00 cmudict.dict
-rw-r--r-- 1 root root  453254 Apr 20 12:34 cmudict.dict.dev.preprocessed
-rw-r--r-- 1 root root 8612997 Apr 20 12:34 cmudict.dict.train.preprocessed
-rw-rw-r-- 1 1000 1000     382 Mar 27 09:00 cmudict.phones
-rw-rw-r-- 1 1000 1000     281 Mar 27 09:00 cmudict.symbols
-rw-rw-r-- 1 1000 1000    1747 Mar 27 09:00 cmudict.vp
```

and the model checkpoint files

```
oot@04a9cdd20f2d:~/g2p-seq2seq# ls /root/data/models/cmudict/
checkpoint                                   model.ckpt-136001.data-00001-of-00002  model.ckpt-164001.meta                 model.ckpt-28001.data-00001-of-00002  model.ckpt-68001.meta
eval                                         model.ckpt-136001.index                model.ckpt-178001.data-00000-of-00002  model.ckpt-28001.index                model.ckpt-82001.data-00000-of-00002
eval.preprocessed                            model.ckpt-136001.meta                 model.ckpt-178001.data-00001-of-00002  model.ckpt-28001.meta                 model.ckpt-82001.data-00001-of-00002
events.out.tfevents.1525271417.dc49bc57cb43  model.ckpt-14001.data-00000-of-00002   model.ckpt-178001.index                model.ckpt-42001.data-00000-of-00002  model.ckpt-82001.index
graph.pbtxt                                  model.ckpt-14001.data-00001-of-00002   model.ckpt-178001.meta                 model.ckpt-42001.data-00001-of-00002  model.ckpt-82001.meta
model.ckpt-110001.data-00000-of-00002        model.ckpt-14001.index                 model.ckpt-192001.data-00000-of-00002  model.ckpt-42001.index                model.ckpt-96001.data-00000-of-00002
model.ckpt-110001.data-00001-of-00002        model.ckpt-14001.meta                  model.ckpt-192001.data-00001-of-00002  model.ckpt-42001.meta                 model.ckpt-96001.data-00001-of-00002
model.ckpt-110001.index                      model.ckpt-150001.data-00000-of-00002  model.ckpt-192001.index                model.ckpt-56001.data-00000-of-00002  model.ckpt-96001.index
model.ckpt-110001.meta                       model.ckpt-150001.data-00001-of-00002  model.ckpt-192001.meta                 model.ckpt-56001.data-00001-of-00002  model.ckpt-96001.meta
model.ckpt-124001.data-00000-of-00002        model.ckpt-150001.index                model.ckpt-200000.data-00000-of-00002  model.ckpt-56001.index                model.params
model.ckpt-124001.data-00001-of-00002        model.ckpt-150001.meta                 model.ckpt-200000.data-00001-of-00002  model.ckpt-56001.meta                 train.preprocessed
model.ckpt-124001.index                      model.ckpt-164001.data-00000-of-00002  model.ckpt-200000.index                model.ckpt-68001.data-00000-of-00002  vocab.g2p
model.ckpt-124001.meta                       model.ckpt-164001.data-00001-of-00002  model.ckpt-200000.meta                 model.ckpt-68001.data-00001-of-00002
model.ckpt-136001.data-00000-of-00002        model.ckpt-164001.index                model.ckpt-28001.data-00000-of-00002   model.ckpt-68001.index
```

But when I try the `--interactive` mode I get the same error.
My `Dockerfile` is [here](https://github.com/loretoparisi/docker/blob/master/g2p-seq2seq/Dockerfile)
I'm using

```
nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
tensor2tensor==1.5.7
tensorflow-gpu==1.4.0
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
@nurtas-m I have finally understood the problem. This is due to TF 1.5.0 breaking changes (support for CUDA 9.0 only), that it is not compatibile with the past ( <= 1.5.0, like the 1.4.x that supports CUDA 8 instead with GPU):


- Having TF 1.4.0 the TRAINING works with GPU, but the INFERENCE does not work (`--interactive`).
- Having TF 1.5.0 the INFERENCE works with CPU from the trained model (1.4.0 / GPU)- see later logging

```
> hello
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
[2018-05-03 09:22:50,513] Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
INFO:tensorflow:Setting T2TModel mode to 'infer'
[2018-05-03 09:22:50,525] Setting T2TModel mode to 'infer'
INFO:tensorflow:Setting hparams.layer_prepostprocess_dropout to 0.0
[2018-05-03 09:22:50,525] Setting hparams.layer_prepostprocess_dropout to 0.0
INFO:tensorflow:Setting hparams.symbol_dropout to 0.0
[2018-05-03 09:22:50,525] Setting hparams.symbol_dropout to 0.0
INFO:tensorflow:Setting hparams.attention_dropout to 0.0
[2018-05-03 09:22:50,525] Setting hparams.attention_dropout to 0.0
INFO:tensorflow:Setting hparams.dropout to 0.0
[2018-05-03 09:22:50,525] Setting hparams.dropout to 0.0
INFO:tensorflow:Setting hparams.relu_dropout to 0.0
[2018-05-03 09:22:50,525] Setting hparams.relu_dropout to 0.0
INFO:tensorflow:Greedy Decoding
[2018-05-03 09:22:50,526] Greedy Decoding
INFO:tensorflow:Restoring parameters from /root/data/models/cmudict/model.ckpt-200000
[2018-05-03 09:22:54,916] Restoring parameters from /root/data/models/cmudict/model.ckpt-200000
Pronunciations: ['HH AH0 L OW1']
```

So at this point, for my configuration I can train with TF 1.4.0 once, and I will do inference on CPU as soon as I can move to CUDA 9.

**Comment by loretoparisi** [comment]
@nshmyrev closing this since it's related to the version of TF and CUDA.
