### ISSUE TITLE
Error in python setup.py test

### ISSUE THREAD

**Issue by Reggyyy** [cmusphinx/g2p-seq2seq#121]
I looks for the tensorflow module even though i have installed it.

(Training) rgb@rgb-HP-Notebook:~/Desktop/Training$ g2p-seq2seq
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.1.4a0', 'console_scripts', 'g2p-seq2seq')()
  File "/home/rgb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rgb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/home/rgb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/rgb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "/usr/local/lib/python2.7/dist-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/app.py", line 29, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

**Comment by nurtas-m** [comment]
Ok, I could reproduce your error. You need to install version of tensor2tensor=1.5.7

**Comment by Reggyyy** [comment]
I've already installed tensorflow 1.5.0 and tensor2tensor 1.5.7

This is now the result for the test:
(TrainingPy2) rgb@rgb-HP-Notebook:~/Desktop/TrainingPy2/g2p-seq2seq$ python setup.py test
running test
running egg_info
writing requirements to g2p_seq2seq.egg-info/requires.txt
writing g2p_seq2seq.egg-info/PKG-INFO
writing top-level names to g2p_seq2seq.egg-info/top_level.txt
writing dependency_links to g2p_seq2seq.egg-info/dependency_links.txt
writing entry points to g2p_seq2seq.egg-info/entry_points.txt
reading manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
running build_ext
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
test_decode (tests.g2p_unittest.TestG2P) ... WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
[2018-05-08 18:02:24,925] Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f7344b11cf8>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:24,925] Estimator's model_fn (<function wrapping_model_fn at 0x7f7344b11cf8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
[2018-05-08 18:02:25,041] From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f7344a102a8>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:25,042] Estimator's model_fn (<function wrapping_model_fn at 0x7f7344a102a8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
[2018-05-08 18:02:25,049] Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
WARNING:tensorflow:From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py:600: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[2018-05-08 18:02:25,240] From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py:600: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/utils/beam_search.py:93: calling reduce_logsumexp (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[2018-05-08 18:02:26,008] From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/utils/beam_search.py:93: calling reduce_logsumexp (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-05-08 18:02:26.202347: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
ok
test_evaluate (tests.g2p_unittest.TestG2P) ... WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
[2018-05-08 18:02:26,589] Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f73419ebc08>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:26,590] Estimator's model_fn (<function wrapping_model_fn at 0x7f73419ebc08>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f73419ebc80>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:26,590] Estimator's model_fn (<function wrapping_model_fn at 0x7f73419ebc80>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
[2018-05-08 18:02:26,613] Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
Words: 3
Errors: 3
WER: 1.000
Accuracy: 0.000
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
[2018-05-08 18:02:28,144] Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
ok
test_train (tests.g2p_unittest.TestG2P) ... WARNING:tensorflow:Schedule=train_and_evaluate. Assuming that training is running on a single machine.
[2018-05-08 18:02:29,706] Schedule=train_and_evaluate. Assuming that training is running on a single machine.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f73433af140>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:29,706] Estimator's model_fn (<function wrapping_model_fn at 0x7f73433af140>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:Estimator's model_fn (<function wrapping_model_fn at 0x7f73433af1b8>) includes params argument, but params are not passed to Estimator.
[2018-05-08 18:02:29,706] Estimator's model_fn (<function wrapping_model_fn at 0x7f73433af1b8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py:1828: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

[2018-05-08 18:02:30,853] From /home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py:1828: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

/home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

**Comment by Reggyyy** [comment]
But when I try the interactive mode:

(TrainingPy2) rgb@rgb-HP-Notebook:~/Desktop/TrainingPy2$ g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/rgb/Desktop/TrainingPy2/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.1.4a0', 'console_scripts', 'g2p-seq2seq')()
  File "/home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/app.py", line 111, in main
    params.hparams = g2p_trainer_utils.load_params(FLAGS.model_dir)
  File "/home/rgb/Desktop/TrainingPy2/local/lib/python2.7/site-packages/g2p_seq2seq-6.1.4a0-py2.7.egg/g2p_seq2seq/g2p_trainer_utils.py", line 210, in load_params
    model_params = json.load(open(params_file_path))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
