### ISSUE TITLE
No module named Tensorboard.backend.event_processing

### ISSUE THREAD

**Issue by prashantserai** [cmusphinx/g2p-seq2seq#127]
Hi,

I just installed this (with Tensorflow 1.6), and got the following error on my first run.

Traceback (most recent call last):
  File ".............bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.2.0a0', 'console_scripts', 'g2p-seq2seq')()
  File ".............lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File ".............lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File ".............lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File ".............lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File ".............lib/python2.7/site-packages/g2p_seq2seq-6.2.0a0-py2.7.egg/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File ".............lib/python2.7/site-packages/g2p_seq2seq-6.2.0a0-py2.7.egg/g2p_seq2seq/app.py", line 31, in <module>
    import g2p_seq2seq.g2p_trainer_utils as g2p_trainer_utils
  File ".............lib/python2.7/site-packages/g2p_seq2seq-6.2.0a0-py2.7.egg/g2p_seq2seq/g2p_trainer_utils.py", line 31, in <module>
    from tensor2tensor.utils import trainer_lib
  File ".............lib/python2.7/site-packages/tensor2tensor-1.6.3-py2.7.egg/tensor2tensor/utils/trainer_lib.py", line 29, in <module>
    from tensor2tensor.utils import metrics_hook
  File ".............lib/python2.7/site-packages/tensor2tensor-1.6.3-py2.7.egg/tensor2tensor/utils/metrics_hook.py", line 26, in <module>
    from tensorboard.backend.event_processing import event_accumulator
ImportError: No module named tensorboard.backend.event_processing

----------------

and there were the following two errors during installation

Installed ............./lib/python2.7/site-packages/h5py-2.8.0rc1-py2.7-linux-x86_                                     64.egg
Searching for gym
Reading https://pypi.python.org/simple/gym/
Downloading https://files.pythonhosted.org/packages/9b/50/ed4a03d2be47ffd043be2ee514f329ce45d98a30fe2d1b9c61dea5a9d861/gy                                     m-0.10.5.tar.gz#sha256=6baf3f3b163e237869d92a64daeaa88f14f62bb1105863e45312505a19dbd652
Best match: gym 0.10.5
Processing gym-0.10.5.tar.gz
Writing /tmp/easy_install-QU4gl7/gym-0.10.5/setup.cfg
Running gym-0.10.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QU4gl7/gym-0.10.5/egg-dist-tmp-S8vYPd
  File "build/bdist.linux-x86_64/egg/gym/utils/reraise_impl_py3.py", line 4
    raise e.with_traceback(traceback) from None
                                         ^
SyntaxError: invalid syntax

creating ............./lib/python2.7/site-packages/gym-0.10.5-py2.7.egg
Extracting gym-0.10.5-py2.7.egg to ............./lib/python2.7/site-packages
  File "............./lib/python2.7/site-packages/gym-0.10.5-py2.7.egg/gym/utils/r                                     eraise_impl_py3.py", line 4
    raise e.with_traceback(traceback) from None
                                         ^
SyntaxError: invalid syntax

**Comment by nurtas-m** [comment]
Hello, @prashantserai 

Can you, please, install tensor2tensor ver=1.5.7?
Current version of g2p-seq2seq is incompatible with tensor2tensor=>1.6.0

**Comment by nurtas-m** [comment]
Hello, @prashantserai 
Can you, please, print out new error message? I want to be sure that g2p-seq2seq calls the right version of tensor2tensor.
