### ISSUE TITLE
Reg: Error during seq2seq model training.

### ISSUE THREAD

**Issue by ellurunaresh** [cmusphinx/g2p-seq2seq#133]
Hi all,
while training the model I was getting the following error. I have followed previous blogs but I couldn't solve the issue. I could see my vocabulary is in ASCII format. I am not sure why I am getting this error.
Please help me out how to solve this issue.
Tensorflow version: 1.3.0

**Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 77, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 198, in create_train_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 170, in __prepare_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/seq2seq_model.py", line 178, in __init__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1195, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1110, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1067, in sequence_loss_by_example
    crossent = softmax_loss_function(target, logit)
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/seq2seq_model.py", line 117, in sampled_loss
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 1191, in sampled_softmax_loss
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 947, in _compute_sampled_logits
    range_max=num_classes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/candidate_sampling_ops.py", line 134, in log_uniform_candidate_sampler
    seed2=seed2, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_candidate_sampling_ops.py", line 357, in _log_uniform_candidate_sampler
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
"ValueError: Shape must be rank 2 but is rank 1 for 'model_with_buckets/sequence_loss/sequence_loss_by_example/sampled_softmax_loss/LogUniformCandidateSampler' (op: 'LogUniformCandidateSampler') with input shapes: [?]"**

**Comment by nurtas-m** [comment]
Hello, @ellurunaresh 
Please, clone the latest version of g2p-seq2seq (6.2.0a0). Also, it is required tensorflow=>1.5.0

**Comment by ellurunaresh** [comment]
Actually I couldn't update tensorflow in my system. Can I solve this
problem without upgradation.

**Comment by ellurunaresh** [comment]
Please help me out.

**Comment by nurtas-m** [comment]
In that case, can you, please, install tensorflow=1.5.0 only for your user (with "--user" flag:  pip install tensorflow==1.5.0 --user) ?

**Comment by ellurunaresh** [comment]
OK sure. Thanks 😊

**Comment by ellurunaresh** [comment]
Hi,
How to handle "_UNK" during decoding. Is there any option to set the parameter so that it could take any nearest string or how to proceed further?

**Comment by ellurunaresh** [comment]
Please let me know how to handle this issue?

**Comment by ellurunaresh** [comment]
If anybody knows the solution please share it.

**Comment by nurtas-m** [comment]
Hello, @ellurunaresh 

> 1. How to handle "_UNK" during decoding. Is there any option to set the parameter so that it could take any nearest string?

1. If you work with the problem with words boundary detection, as I had mention in [https://github.com/cmusphinx/g2p-seq2seq/issues/126#issuecomment-395933356](issue #126), you don't need to consider any decoded symbols except "SPACE" symbol. The only information you have to utilize is the **position** of "SPACE" symbol. For example, you feed to the program following input sequence for decoding:
> goodafternoon

And, let's say, you receive following decoded sequence with "UNK" symbols:
decodes = ["g", "o", "o", "UNK", "SPACE", "a", "v", "t", "UNK", "r", "n", "o", "e", "n"]

You, should take just "SPACE" symbols **positions** in decoded symbols: 
`space_positions = [sym_pos for sym_pos, sym in enumerate(decodes) if sym == 'SPACE']`

In the above example, "SPACE" symbol in decodes occurs on 4th position:
`print(space_positions)`
`[4]`

So, you should build output sequence from **input** sequence (not decoded sequence with "UNK" and other decoded symbols). And, just add white-space character in the positions where "SPACE" character found previously:
`output_str = ""`
`for pos, sym in enumerate(inputs):`
`....if pos in space_positions:`
`........output_str += " "`
`....output_str += sym`
`print("Input:{}".format("".join(inputs)))`
`print("Output:{}".format(output_str))`

> 2. During training can I generate "embeddings" for all unknown words?

Generation and utilizing embeddings outside of tensor2tensor is problematic due to applying not only tokens but also sub-tokens for building vocabularies: https://github.com/tensorflow/tensor2tensor/issues/173
