### ISSUE TITLE
TypeError: create_run_config() takes at least 1 argument (24 given)

### ISSUE THREAD

**Issue by embie27** [cmusphinx/g2p-seq2seq#158]
When running the command line program or even the tests with `python setup.py test` i get the following error:
```
running test
running egg_info
writing requirements to g2p_seq2seq.egg-info/requires.txt
writing g2p_seq2seq.egg-info/PKG-INFO
writing top-level names to g2p_seq2seq.egg-info/top_level.txt
writing dependency_links to g2p_seq2seq.egg-info/dependency_links.txt
writing entry points to g2p_seq2seq.egg-info/entry_points.txt
reading manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'g2p_seq2seq.egg-info/SOURCES.txt'
running build_ext
test_decode (tests.g2p_unittest.TestG2P) ... ERROR
test_evaluate (tests.g2p_unittest.TestG2P) ... ERROR
test_train (tests.g2p_unittest.TestG2P) ... ERROR

======================================================================
ERROR: test_decode (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/tests/g2p_unittest.py", line 34, in test_decode
    g2p_model = G2PModel(params, test_path=decode_file_path)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() takes at least 1 argument (24 given)

======================================================================
ERROR: test_evaluate (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/tests/g2p_unittest.py", line 47, in test_evaluate
    g2p_model = G2PModel(params, test_path=gt_path)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() takes at least 1 argument (24 given)

======================================================================
ERROR: test_train (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/tests/g2p_unittest.py", line 23, in test_train
    test_path=dev_path)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 77, in __init__
    self.__prepare_model(train_mode=True)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() takes at least 1 argument (24 given)

----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
```

In the code it looks like there is missing a non-optional argument. Any ideas?

**Comment by nshmyrev** [comment]
Wrong tensor2tensor version. Try 1.6.6
