### ISSUE TITLE
Error with freezing graph

### ISSUE THREAD

**Issue by embie27** [cmusphinx/g2p-seq2seq#159]
When trying to freeze my trained model I get the following error:
```
Traceback (most recent call last):
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.2.2a0', 'console_scripts', 'g2p-seq2seq')()
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/g2p_seq2seq-6.2.2a0-py2.7.egg/g2p_seq2seq/app.py", line 120, in main
    g2p_model.freeze()
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/g2p_seq2seq-6.2.2a0-py2.7.egg/g2p_seq2seq/g2p.py", line 377, in freeze
    clear_devices=clear_devices)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
    **kwargs)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/emil/Dokumente/RaspberryPi/Francis/g2p-test/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'IteratorV2'
```
My tensorflow version is 1.9.0, also tried with 1.8.0. tensor2tensor is 1.6.6.

**Comment by nshmyrev** [comment]
Same as #149
