### ISSUE TITLE
TypeError: create_run_config() got an unexpected keyword argument 'shard_to_cpu'

### ISSUE THREAD

**Issue by darth-willy** [cmusphinx/g2p-seq2seq#168]
I just tried running the tests using `sudo python setup.py test` and got the following error, which is seems related to the fact that the `shard_to_cpu` parameter was [removed a while ago](https://github.com/tensorflow/tensor2tensor/commit/b3fcb473d4285c3159fb6eee5262c64187d71268). After removing the referred line in `g2p_trainer_utils.py` it works fine.

```
test_decode (tests.g2p_unittest.TestG2P) ... ERROR
test_evaluate (tests.g2p_unittest.TestG2P) ... ERROR
test_train (tests.g2p_unittest.TestG2P) ... ERROR

======================================================================
ERROR: test_decode (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/william/speech/sphinx/g2p-seq2seq/tests/g2p_unittest.py", line 34, in test_decode
    g2p_model = G2PModel(params, test_path=decode_file_path)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() got an unexpected keyword argument 'shard_to_cpu'

======================================================================
ERROR: test_evaluate (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/william/speech/sphinx/g2p-seq2seq/tests/g2p_unittest.py", line 47, in test_evaluate
    g2p_model = G2PModel(params, test_path=gt_path)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() got an unexpected keyword argument 'shard_to_cpu'

======================================================================
ERROR: test_train (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/william/speech/sphinx/g2p-seq2seq/tests/g2p_unittest.py", line 23, in test_train
    test_path=dev_path)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 77, in __init__
    self.__prepare_model(train_mode=True)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/william/speech/sphinx/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 230, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() got an unexpected keyword argument 'shard_to_cpu'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
```

**Comment by nshmyrev** [comment]
Thank you for reporting this issue. Please submit a pull request to update the t2t version and remove unused parameter.

**Comment by darth-willy** [comment]
Ok, done

**Comment by renan-cunha** [comment]
I run for the same problem and now is appearing:

**Comment by william-vw** [comment]
I don't think that the pull request has been merged yet - but in the meantime you can simply remove the referred line from `g2p_trainer_utils.py`.

**Comment by agadooPineapple** [comment]
I am running in a python 3.5 virtual environment and have the same error as @renan-cunha . After removing line 217 (cpu shard) as suggested and running the test again I have the following output:

```
test_decode (tests.g2p_unittest.TestG2P) ... ERROR
test_evaluate (tests.g2p_unittest.TestG2P) ... ERROR
test_train (tests.g2p_unittest.TestG2P) ... ERROR

======================================================================
ERROR: test_decode (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/tests/g2p_unittest.py", line 34, in test_decode
    g2p_model = G2PModel(params, test_path=decode_file_path)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 229, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() missing 1 required positional argument: 'model_name'

======================================================================
ERROR: test_evaluate (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/tests/g2p_unittest.py", line 47, in test_evaluate
    g2p_model = G2PModel(params, test_path=gt_path)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 89, in __init__
    self.__prepare_model()
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 229, in create_run_config
    use_tpu=params.use_tpu)
TypeError: create_run_config() missing 1 required positional argument: 'model_name'

======================================================================
ERROR: test_train (tests.g2p_unittest.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/tests/g2p_unittest.py", line 23, in test_train
    test_path=dev_path)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 77, in __init__
    self.__prepare_model(train_mode=True)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p.py", line 102, in __prepare_model
    self.params)
  File "/home/ash/Downloaded_programs/p3_5s2s/g2p-seq2seq/g2p_seq2seq/g2p_trainer_utils.py", line 229, in create_run_configstuff 
    use_tpu=params.use_tpu)
TypeError: create_run_config() missing 1 required positional argument: 'model_name'

----------------------------------------------------------------------
Ran 3 tests in 0.005s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
```
@william-vw did you need to change anything else to get it to work?

**Comment by agadooPineapple** [comment]
I was using the latest tensorflow and tensor2tensor version 1.12.0 I found downgrading to 1.9.0 for both I don't even have to remove line 217, I still get errors/warnings but 2/3 tests are passing now.

**Comment by william-vw** [comment]
No, I didn't have to do anything else to get it to work .. 

My setup: 
- g2p-seq2seq version = 6.2.2a0
- tensorflow version = 1.12.0rc2
- tensor2tensor version = 1.6.6

**Comment by mondhs** [comment]
Just to add some details. Hope it helps, I also received errors with   'shard_to_cpu'. After I applied fix manually I got error with 'model_name', when running test. 
When I check versions:
``` 
tensor2tensor            1.12.0                           
tensorflow               1.12.0             
g2p-seq2seq              6.2.2a0  
```

So I downgraded tensor2tensor to `1.6.6` and now tests are passing.
