### ISSUE TITLE
The 'numpy' distribution was not found and is required by tensor2tensor

### ISSUE THREAD

**Issue by Esarve** [cmusphinx/g2p-seq2seq#180]
Hi 
I am quite new to CMU Sphinx and I am trying to build a phonetic dictionary for my language with g2p-seq2seq. I am facing this error when I try to run this command

> g2p-seq2seq bangla_test1.lm bangla/

And I get this Error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tensor2tensor 1.13.4 (/usr/lib/python3.7/site-packages), Requirement.parse('tensor2tensor<=1.7.0,>=1.6.6'), {'g2p-seq2seq'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/g2p-seq2seq", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'numpy' distribution was not found and is required by tensor2tensor

I have tried various versions of tensor2tensor(1.7.0, The Latest One, and some others). Can anyone assist me on this problem?

**Comment by nshmyrev** [comment]
It says you need numpy, not really related to this codebase.
