### ISSUE TITLE
g2p-seq2seq --interactive --model error

### ISSUE THREAD

**Issue by temitopefunmi** [cmusphinx/g2p-seq2seq#182]
I tried to run g2p-seq2seq --interactive --model_dir g2p-seq2seq-cmudict but i get the error:
Traceback (most recent call last):
File "C:\Users\HP\Anaconda3\envs\my-env\Scripts\g2p-seq2seq-script.py", line 11, in 
load_entry_point('g2p-seq2seq==6.0.0a0', 'console_scripts', 'g2p-seq2seq')()
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources_init_.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources_init_.py", line 2852, in load_entry_point
return ep.load()
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources_init_.py", line 2443, in load
return self.resolve()
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\pkg_resources_init_.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq_init_.py", line 24, in 
from g2p_seq2seq import app
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq\app.py", line 31, in 
from g2p_seq2seq.g2p import G2PModel
File "C:\Users\HP\Anaconda3\envs\my-env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.6.egg\g2p_seq2seq\g2p.py", line 30, in 
from tensor2tensor.utils import trainer_utils
ImportError: cannot import name 'trainer_utils'

Please what do i do?

**Comment by nshmyrev** [comment]
Same as https://github.com/cmusphinx/g2p-seq2seq/issues/107#issuecomment-528247729, you just need a proper tensor2tensor and tensorflow versions. It will not yet work with newer version. Software needs update.

**Comment by temitopefunmi** [comment]
I saw this thread already so I installed tensor2tensor = 1.5.7. But tensorflow is 1.14.0

**Comment by nshmyrev** [comment]
The tool requires TensorFlow version 1.8.0 and Tensor2Tensor version 1.6.6

**Comment by temitopefunmi** [comment]
I have now installed these two versions and still the same issue

**Comment by nshmyrev** [comment]
Show updated output

**Comment by temitopefunmi** [comment]
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\tf_env\Scripts\g2p-seq2seq-script.py", line 11, in <module>
    load_entry_point('g2p-seq2seq==6.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\pkg_resources\__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\pkg_resources\__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\pkg_resources\__init__.py", line 2332, in load
    return self.resolve()
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\pkg_resources\__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.5.egg\g2p_seq2seq\__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.5.egg\g2p_seq2seq\app.py", line 31, in <module>
    from g2p_seq2seq.g2p import G2PModel
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.5.egg\g2p_seq2seq\g2p.py", line 28, in <module>
    from g2p_seq2seq import g2p_trainer_utils
  File "C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.5.egg\g2p_seq2seq\g2p_trainer_utils.py", line 26, in <module>
    from tensor2tensor.utils import input_fn_builder
ImportError: cannot import name 'input_fn_builder'

**Comment by nshmyrev** [comment]
Remove C:\Users\HP\Anaconda3\envs\tf_env\lib\site-packages\g2p_seq2seq-6.0.0a0-py3.5.egg and install the code from git clone, not with a pip, looks like the version you have is outdated.

**Comment by temitopefunmi** [comment]
Works now. Thank you so much
