### ISSUE TITLE
Train with short dictionaries

### ISSUE THREAD

**Issue by nshmyrev** [cmusphinx/g2p-seq2seq#38]
```
Traceback (most recent call last):
  File "g2p.py", line 442, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "g2p.py", line 425, in main
    g2p_model.train(g2p_params, FLAGS.train, FLAGS.valid, FLAGS.test)
  File "g2p.py", line 243, in train
    self.__run_evals()
  File "g2p.py", line 269, in __run_evals
    self.valid_set, bucket_id)
  File "/usr/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 252, in get_batch
    encoder_input, decoder_input = random.choice(data[bucket_id])
  File "/usr/lib64/python2.7/random.py", line 274, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

**Comment by faizann24** [comment]
Why does this occur. It is occuring to me.

**Comment by faizann24** [comment]
Apologies but I can't seem to find a solution of the problem.

**Comment by nshmyrev** [comment]
For solution use bigger base dictionary

**Comment by faizann24** [comment]
What's the minimum size for the dictionary.

**Comment by faizann24** [comment]
One more thing, is it necessary to add "VOWEL", "FRICATIVE" etc in .phones file.

Best REGARDS.

**Comment by faizann24** [comment]
I tried using a 6 m.b dictionary. Still the same issue.

**Comment by nshmyrev** [comment]
You can share your dictionary to help us fix this problem

**Comment by faizann24** [comment]
[Github_Dic.txt](https://github.com/cmusphinx/g2p-seq2seq/files/364797/Github_Dic.txt)
Here's a small part of it.

**Comment by faizann24** [comment]
[Phones_Github.txt](https://github.com/cmusphinx/g2p-seq2seq/files/364800/Phones_Github.txt)
Phones file.

**Comment by faizann24** [comment]
This is the full error. Its not exactly the same as mentioned in this post.

Created model with fresh parameters.
global step 200 learning rate 0.5000 step-time 1.24 perplexity 61.18
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 67, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 217, in train
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 253, in __run_evals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 250, in get_batch
    encoder_input, decoder_input = random.choice(data[bucket_id])
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range

**Comment by nshmyrev** [comment]
ok, there is no need to past same errors again and again, be patient

**Comment by nshmyrev** [comment]
This issue should be fixed now. Update and try again.

**Comment by faizann24** [comment]
Thanks a lot. Apologies for bothering.

Will let you know after checking.

Best Regards.
