### ISSUE TITLE
Running question for this command(g2p-seq2seq --interactive --model model_folder_path)

### ISSUE THREAD

**Issue by SHU-HAN** [cmusphinx/g2p-seq2seq#41]
```
sam@speechws13:~/g2p-seq2seq-master$ g2p-seq2seq --interactive --model g2p-seq2seq-cmudict/g2p-seq2seq-cmudict/modle
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/__init__.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 36, in <module>
ImportError: No module named data_utils
```

how can I fix this question??
thank you~

**Comment by nshmyrev** [comment]
Are you sure you are using latest version please? It does not look like that, it seems you have slightly older one. Could you reinstall?

g2p.py should contain the line

`from g2p_seq2seq import data_utils
`
not

`import data_utils
`

**Comment by SHU-HAN** [comment]
I'm so sorry
I didn't notice that,because I was studying your g2p.py and tried to fix that problem 
So I change the code
Thank you for reminding me
It's work now

Thank You,Best Regards

**Comment by nshmyrev** [comment]
Ok, let me know if you have further questions

**Comment by SHU-HAN** [comment]
sorry~ I don't know what happened when i was training chinese language
 model
I gave chinese  dictionary(like example dictionary)  & empty dir(chmodel)
and  the dict has been transform to unicode

then i got this error message,what is that mean??

sam@speechws13:~/g2p-seq2seq$ sudo g2p-seq2seq --train dict.dic --model
chmodel/
Preparing G2P data
Creating vocabularies in chmodel/
Creating vocabulary chmodel/vocab.phoneme
Creating vocabulary chmodel/vocab.grapheme
Reading development and training data.
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op
parallelism threads: 8
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter
op parallelism threads: 8
Creating 2 layers of 64 units.
Created model with fresh parameters.
global step 200 learning rate 0.5000 step-time 1.85 perplexity 99.10
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts',
'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 67, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 221, in train
*TypeError: save() got an unexpected keyword argument 'write_meta_graph'*
sam@speechws13:~/g2p-seq2seq$


2016-07-12 21:10 GMT+08:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
Your tensorflow is too old, you need version 0.9.
