### ISSUE TITLE
coding problem

### ISSUE THREAD

**Issue by yfliao** [cmusphinx/g2p-seq2seq#44]
Dear All,

I got a coding error in test phase (training and interactive phase were all fine). My training dictionary  is a mixture of cmudict (ascii) and Chinese (utf-8) lexicons. What should I do? Should I convert all cmudict entries to utf-8?

Thanks a lot in advance!

Here is the log:
---
global step 91200 learning rate 0.2425 step-time 0.13 perplexity 1.02
Training done.
Creating 2 layers of 512 units.
Reading model parameters from g2p-seq2seq-oc16
Beginning calculation word error rate (WER) on test sample.
Traceback (most recent call last):
  File "/home/liao/anaconda3/envs/python2.7/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 67, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 234, in train
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 347, in evaluate
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 323, in calc_error
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 279, in decode_word
UnicodeEncodeError: 'ascii' codec can't encode character u'\u86c8' in position 9: ordinal not in range(128)

Here is my training dictionary:
---
瘦西湖 sh ou4 x i1 h u2
睃 s uo1
supercuts S UW1 P ER0 K AH2 T S
电报机 d ian4 b ao4 j i1
galka G AE1 L K AH0
知 zh ix4
Unipus  Y UW1 N IH0 P AH0 S

**Comment by nurtas-m** [comment]
Hello, yfliao!
Coding problem fixed. Can you check, please?
