### ISSUE TITLE
Not descriptive error message when model is missing in the folder

### ISSUE THREAD

**Issue by gkm2709** [cmusphinx/g2p-seq2seq#55]
Hello,

I am trying to run the command 

g2p-seq2seq --interactive --model ../g2p-seq2seq-cmudict/model

with the model suggested for download on https://github.com/cmusphinx/g2p-seq2seq

and see following error 

user@machine:~/Desktop/sphinx-source/g2p-seq2seq$ sudo g2p-seq2seq --interactive --model ../g2p-seq2seq-cmudict/model
> test
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 78, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 315, in interactive
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 277, in decode_word
AttributeError: 'G2PModel' object has no attribute 'gr_vocab'

Please help.

**Comment by gkm2709** [comment]
I realize the mistake... I should only provide the name of the directory and not model..

**Comment by nshmyrev** [comment]
Actually error message should be more descriptive. Thank you for the report!

**Comment by gkm2709** [comment]
Yes Indeed a more descriptive error message would have helped to debug easily... However, it was purely my ignorance to run into this problem..

**Comment by nshmyrev** [comment]
```
g2p-seq2seq --interactive
Traceback (most recent call last):
  File "/home/shmyrev/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 79, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 75, in load_decode_model
RuntimeError: Model not found in None

```
If model is not specified it should not write 'None'

**Comment by nurtas-m** [comment]
Close with commit: https://github.com/cmusphinx/g2p-seq2seq/commit/20dc69f3d4104bdfe668056e652ede6a8183130f
